env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent: [error, 2]
  quotes: [warn, single]
  semi: [error, never]
  comma-dangle: [warn, only-multiline]
  no-console: [off]